######################Example################################
#                                                           #
#                Application Name:                          #
#                 - Developer                               #
#                 - Direct Download Link                    #
#                 - Files type(tar.gz recommended)          #
#                                                           #
#                                                           #
#                                                           #
#############################################################                                                            


# please make sure the packages you save are secure


code:
- Microsoft 
- https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
- .tar.gz
- vscode

eclipse:
- Eclipse Fondation
- https://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz
- .tar.gz
- eclipse

glue-git:
- Elagoht
- https://codeload.github.com/Elagoht/Glue/tar.gz/refs/tags/v1.0
- .tar.gz
- glue-git

sudo-mice:
- Elagoht
- https://github.com/Elagoht/SudoMice/releases/download/v1.0/SudoMice.tar.gz
- .tar.gz
- sudo-mice

discord:

- discord
- https://discord.com/api/download?platform=linux&format=tar.gz
- .tar.gz
- discord

brave:

- Brave
- https://github.com/brave/brave-browser/releases/download/v1.47.85/brave-browser-nightly-1.47.85-linux-amd64.zip
- .zip
- brave






########################################################################################################################################
                                                        #DEBIAN#
########################################################################################################################################

opera:

- opera
- https://download.opera.com/download/get/?id=59544&location=424&nothanks=yes&sub=marine&utm_tryagain=yes
- .deb
- opera
