######Example#######

#Application Name:
# - Developer
# - Direct Download Link
# - Files type(tar.xz recommended)


code:
- Microsoft 
- https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
- .tar.xz
- vscode 

eclipse:
- Eclipse Fondation
- https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz&mirror_id=1045
- .tar.xz
- Eclipse