######################Example################################
#                                                           #
#                Application Name:                          #
#                 - Developer                               #
#                 - Direct Download Link                    #
#                 - Files type(tar.gz recommended)          #
#                                                           #
#                                                           #
#                                                           #
#############################################################                                                            


# please make sure the packages you save are secure


vscode:
- Microsoft 
- https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
- .tar.gz
- vscode

eclipse:
- Eclipse Fondation
- https://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz
- .tar.gz
- eclipse

glue-git:
- Elagoht
- https://codeload.github.com/Elagoht/Glue/tar.gz/refs/tags/v1.0
- .tar.gz
- glue-git

sudo-mice:
- Elagoht
- https://github.com/Elagoht/SudoMice/releases/download/v1.0/SudoMice.tar.gz
- .tar.gz
- sudo-mice

discord:

- discord
- https://discord.com/api/download?platform=linux&format=tar.gz
- .tar.gz
- discord

brave:

- Brave
- https://github.com/brave/brave-browser/releases/download/v1.47.85/brave-browser-nightly-1.47.85-linux-amd64.zip
- .zip
- brave

intellij idea:

- JetBrains
- https://download.jetbrains.com/idea/ideaIU-2022.2.3.tar.gz
- .tar.gz
- idea

pycharm:

- JetBrains
- https://download.jetbrains.com/python/pycharm-professional-2022.2.4.tar.gz
- .tar.gz
- pycharm

filezilla:

- FilleZilla
- https://dl3.cdn.filezilla-project.org/client/FileZilla_3.62.1_i686-linux-gnu.tar.bz2?h=xn-otEQIKApS9hie3JBRdA&x=1669045817
- .tar.bz2
- filezilla

opera:

- opera
- https://download.opera.com/download/get/?id=59544&location=424&nothanks=yes&sub=marine&utm_tryagain=yes
- .deb
- opera

kdenlive:

- KdenLive
- https://download.kde.org/stable/kdenlive/22.08/linux/kdenlive-22.08.3-x86_x64.AppImage
- .AppImage
- kdenlive

openshot:

- OpenShot
- https://github.com/OpenShot/openshot-qt/releases/download/v2.6.1/OpenShot-v2.6.1-x86_64.AppImage
- .AppImage
- openshot

chrome.deb:

- Google
- https://www.google.com/intl/tr_tr/chrome/thank-you.html?statcb=0&installdataindex=empty&defaultbrowser=0#
- .deb
- chrome

chrome.rpm:

- Google
- https://www.google.com/intl/tr_tr/chrome/thank-you.html?statcb=0&installdataindex=empty&defaultbrowser=0#
- .rpm
- chrome

clion:

- JetBrains
- https://download.jetbrains.com/cpp/CLion-2022.2.4.tar.gz
- .tar.gz
- clion

goland:

- JetBrains
- https://download.jetbrains.com/go/goland-2022.2.4.tar.gz
- .tar.gz
- goland

ventoy:

- Ventoy
- https://github.com/ventoy/Ventoy/releases/download/v1.0.82/ventoy-1.0.82-linux.tar.gz
- .tar.gz
- ventoy

codeblocks:
- CodeBlocks
- https://downloads.sourceforge.net/project/codeblocks/Binaries/20.03/Linux/Debian%209/codeblocks_20.03_amd64_oldstable.tar.xz?ts=gAAAAABje5TuBQsqWYjRleZeT963uOWmOirZzCxro1kStOJaTy0eNLXntrcXfIW8KiTcy2nVLBSmjuAoGZ4yzHYOzp1D7MrR0Q%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fcodeblocks%2Ffiles%2FBinaries%2F20.03%2FLinux%2FDebian%25209%2Fcodeblocks_20.03_amd64_oldstable.tar.xz%2Fdownload
- .tar.xz
- codeblocks

rider:

- JetBrains
- https://download.jetbrains.com/rider/JetBrains.Rider-2022.2.4.tar.gz
- .tar.gz
- rider

rubymine:

- JetBrains
- https://download.jetbrains.com/ruby/RubyMine-2022.2.3.tar.gz
- .tar.gz
- rubymine

python:

- Python
- https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
- .tar.xz
- python

golang:

- Gooogle
- https://go.dev/dl/go1.19.3.linux-amd64.tar.gz
- .tar.gz
- golang

steam:

- Valve
- https://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz
- .tar.gz
- steam

heroic: 

- Heroic
- https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.4.3/Heroic-2.4.3.AppImage
- .AppImage
- heoiclauncher

android studio:

- Google 
- https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.17/android-studio-2021.3.1.17-linux.tar.gz
- .tar.xz
- androidstudio

firefox:

- Mozilla
- https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=tr
- .tar.bz2
- firefox

qbittorent:

- Qbittorent
- https://www.fosshub.com/qBittorrent.html?dwl=qbittorrent-4.4.5_x86_64.AppImage
- .AppImage
- Qbittorent

#########################################################################################################################################
                                                    #NORTH APP MANAGER UPDATE SYSTEM#
#########################################################################################################################################

sources:
- NorthLight15
- https://github.com/NorthLight15/North-App-Manager/blob/main/AppSources/sources.yaml
- .yaml
- sources
