######Example#######

#Application Name:
# - Developer
# - Direct Download Link
# - Files type(tar.gz recommended)


code:
- Microsoft 
- https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
- .tar.gz
- vscode

eclipse:
- Eclipse Fondation
- https://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz
- .tar.gz
- eclipse

glue-git:
- Elagoht
- https://codeload.github.com/Elagoht/Glue/tar.gz/refs/tags/v1.0
- .tar.gz
- glue-git

sudo-mice:
- Elagoht
- https://github.com/Elagoht/SudoMice/releases/download/v1.0/SudoMice.tar.gz
- .tar.gz
- sudo-mice
